### PR TITLE
Allow to use without required prefix

### PR DESCRIPTION
**Pull request by hcl-dr**
Some use cases will need this for legacy compatibility

### CODE REVIEW

**Comment by ninjafinne** [comment]
Nvram doesn't really manage duplicate key names between user/system partitions well. The prefix is a safeguard against user mistakes.
Preferably the method for managing legacy compatibility would fit better into code base without conditionally including parts and decreasing maintainability.
Could it be an option to expose the system prefix as an overridable compile time variable (NVRAM_SYSTEM_PREFIX ?= SYS_)?

**Comment by hcl-dr** [comment]
Problem is that there is no fixed prefix for sys entries

**Comment by ninjafinne** [comment]
Check if this meets needs:
https://github.com/data-respons-solutions/nvram/tree/feature/config-sys-prefix

make NVRAM_SYSTEM_PREFIX=""

**Comment by hcl-dr** [comment]
Can not use a fixed prefix, it varies and needs legacy compatibility😟

**Comment by ninjafinne** [comment]
Setting an empty string disables prefix enforcement.

**Comment by hcl-dr** [comment]
And entries written as --sys can _not_ be overwritten/masked by user?

**Comment by ninjafinne** [comment]
They shouldn't be possible to overwrite. However no test coverage for that scenario without the prefix.
Having multiple values may cause confusion:
$ nvram --sys --set TESTSYS 123
$ nvram --set TESTSYS 456
$ nvram --list
TESTSYS=123
TESTSYS=456
$ nvram --get TESTSYS
123

**Pull request closed without merging**
